### ISSUE TITLE
Use `.find()` instead of `.filter()` followed by `[0]`.

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multimatrix#119]
Use `.find()` instead of `.filter()` followed by `[0]`.

Also fix in `_defineNeighbors()`.

_Originally posted by @waxlamp in https://github.com/multinet-app/multimatrix/pull/110#r517633494_

**Comment by mozartfish** [comment]
This issue is resolved with this commit https://github.com/multinet-app/multimatrix/pull/110/commits/7d6d9cd1dee95145a42cb8131031ebc61398fc24. @JackWilb @waxlamp there is still an issue with the node._id and node.id which is why we need two functions defined neighbors and defined superneighbors so I think this problem might be able to be resolved in the re-architecting of the matrix
